# Generated by Django 4.0.4 on 2022-05-22 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_meal_options_rename_appetizer_order_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='kind',
            field=models.CharField(choices=[('appetizers', 'appetizers'), ('entrees', 'entrees'), ('sides', 'sides'), ('other', 'other'), ('rice', 'rice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(default='appetizer', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='cook',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Cooks'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='table',
            name='server',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Servers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
