# Generated by Django 4.0.4 on 2022-05-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='delete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
