# Generated by Django 4.0.4 on 2022-05-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_order_delete_alter_table_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delete',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='delete',
            new_name='deleted',
        ),
    ]
