# Generated by Django 4.0.4 on 2022-05-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_rename_delete_order_deleted_and_more'),
    ]

    operations = [
    ]
