# Generated by Django 4.0.4 on 2022-05-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_table_cook_alter_table_server'),
    ]

    operations = [
    ]
