# Generated by Django 4.0.4 on 2022-05-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20220526_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('server', 'server'), ('cook', 'cook'), ('manager', 'manager'), ('hostess', 'hostess')], default='server', max_length=20),
            preserve_default=False,
        ),
    ]
