# Generated by Django 4.0.4 on 2022-05-28 09:19

import django.core.validators
from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('server', 'server'), ('cook', 'cook'), ('manager', 'manager'), ('hostess', 'hostess')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=restaurant.models.NameField(help_text='Use the following format: firstname_surname', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Use the following format: firstname_surname', regex='^[a-z]_[a-z]$')]),
        ),
    ]
